In [19]:
from sklearn.cluster import KMeans
from sklearn import cluster
from sklearn import datasets
iris = datasets.load_iris()   #Se carga la base de datos
X = iris.data       #La matriz de datos (solo se toman 2 carac. para la visualización)
y = iris.target               #las etiquetas

num_cluster = 8


#init establece el método de localizacion inicial de los centroides
modelo_kmeans= KMeans(init = 'k-means++',n_clusters = num_cluster)

#entrenar el modelo 
modelo_kmeans.fit(X)

#centros
centroides = modelo_kmeans.cluster_centers_

Kmod = modelo_kmeans.labels_

#pruebas de comprobacion de las etiquetas con los centroides
import pandas  as pd 
pd.crosstab(y,Kmod)

col_0   0   1   2   3   4   5   6   7
row_0
0       0  23   0  27   0   0   0   0
1      15   0   3   0   0  20  12   0
2       0   0  15   0  10   1   0  24